journal_apprentissage/journal_apprentissage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('utilisateurs/', include('utilisateurs.urls')),
    path('', include('journaux_apprentissage.urls')),
]

journal_apprentissage/journaux_apprentissage/urls.py
"""Definir des motifs d'URL pour journaux_apprentissage"""

from django.urls    import path
from .              import views

app_name = 'journaux_apprentissage'

urlpatterns = [
    # Page d'accueil:
    path('', views.index, name='index'),

    # Page d'affichage de touts les sujets.
    path('topics/', views.topics, name='topics'),

    # Page d'affichage des détails d'un seul sujet.
    path('topics/<int:topic_id>/', views.topic, name='topic'),

    # Page d'ajout d'un nouveau sujet.
    path('new_topic/', views.new_topic, name='new_topic'),

    # Page d'ajout d'une nouvelle entrée.
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),

    # Page de modification d'une entrée.
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

journal_apprentissage/utilisateurs/urls.py
"""Définir des motifs d'urls pour utilisateur"""

from django.urls    import path, include
from .              import views

app_name = 'utilisateurs'

urlpatterns = [
    # Inclure les URL d'auhtentification par défault:
    path('',include('django.contrib.auth.urls')),
    
    # Page d'inscription:
    path('register/', views.register, name='register'),
]

journal_apprentissage/journaux_apprentissage/models.py
from django.db                  import models
from django.contrib.auth.models import User

# Creation des modéles.
class Topic(models.Model):
    """Sujet sur lequel l'utilisateur se documente."""
    
    # Stocke le nom du topic (max: 200 caracteres):
    text = models.CharField(max_length=200)
    # Fixe automatiquement l'heure courante lors de la creation d'un nv sujet:
    date_added = models.DateTimeField(auto_now_add=True)
    # Supprime tous les éléments liées a l'utilisateur:
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Retourne une representation textuelle du modele."""
        return self.text
    
class Entry(models.Model):
    """Une information apprise sur le sujet."""
    
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    
    # Stocke du texte (taille indéfinie gerée):
    text = models.TextField()
    
    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):
        """Retourne une representation textuelle des 50 premiers mots."""
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        return self.text

journal_apprentissage/utilisateurs/models.py
from django.db import models

# Create your models here.

journal_apprentissage/journaux_apprentissage/forms.py
from django import forms # type: ignore
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets =  {'text': forms.Textarea(attrs={'cols': 80})}

journal_apprentissage/journaux_apprentissage/views.py
from django.shortcuts               import render, redirect
from django.contrib.auth.decorators import login_required
from django.http                    import Http404
from .models                        import Topic, Entry
from .forms                         import TopicForm, EntryForm


def index(request):
    """Page d'accueil pour Journal d'apprentissage."""
    return render(request, 'journaux_apprentissage/index.html')

@login_required
def topics(request):
    """Afficher tous les sujets."""
    
    # topics = Topic.objects.order_by('date_added')
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'journaux_apprentissage/topics.html', context) 


@login_required
def topic(request, topic_id):
    """Afficher un seul sujet et toutes ses entrées."""
    
    topic = Topic.objects.get(id=topic_id)
    
    # Vérifier que le sujet appartient a l'utilisateur courant:
    if topic.owner != request.user:
        raise Http404
    
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'journaux_apprentissage/topic.html', context)


@login_required
def new_topic(request):
    """Ajouter un nouveaux sujet."""
    
    if request.method != 'POST':
        # Aucune données soumise, créer un formulaire vierge:
        form = TopicForm()
    else:
        # Donnees POST soumises, les traiter:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            form.save()
            return redirect('journaux_apprentissage:topics')
        
    # Affiche un formulaire vierge ou invalide:
    context = {'form': form}
    return render(request, 'journaux_apprentissage/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Ajouter une nouvelle entrée a un sujet precis."""
    
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # Aucune données soumise, créer un formulaire vierge:
        form = EntryForm()
    else:
        # Donnees POST soumises, les traiter:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('journaux_apprentissage:topic', topic_id=topic_id)

    # Affiche un formulaire vierge ou invalide:
    context = {'topic': topic, 'form': form}
    return render(request, 'journaux_apprentissage/new_entry.html', context)
         
         
@login_required
def edit_entry(request, entry_id):
    """Modifier une entrée existante."""
    
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if topic.owner != request.user:
        # Vérifiez que le sujet appartient a l'utilisateur courant:
        raise Http404
    
    if request.method != 'POST':
        # Requete initiale, remplir le formulaire avec l'entrée actuelle:
        form = EntryForm(instance=entry)
    else:
        # Donnees POST soumises, les traiter:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('journaux_apprentissage:topic', topic_id=topic.id)
        
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'journaux_apprentissage/edit_entry.html', context)
        

journal_apprentissage/utilisateurs/views.py
from django.shortcuts           import render, redirect
from django.contrib.auth        import login
from django.contrib.auth.forms  import UserCreationForm

# Create your views here.
def register(request):
    """Inscrire un nouvel utilisateur."""
    if request.method != 'POST':
        # Afficher un formulaire d'inscription vide:
        form = UserCreationForm()
    else:
        # Traiter le formulaire rempli:
        form = UserCreationForm(data=request.POST)
        
        if form.is_valid():
            new_user = form.save()
            # Ouvrir session de l'utilisateur et diriger vers la page accueil:
            login(request, new_user)
            return redirect('journaux_apprentissage:index')
        
    # Afficher un formuliare vierge ou invalide:
    context = {'form': form}
    return render(request, 'registration/register.html', context)
            

journal_apprentissage/journaux_apprentissage/templates/journaux_apprentissage/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name"viewport" content="width=device-width, 
        initial-scale=1, shrink-to-fit=no">
    <title>Journal d'apprentissage</title> 
    
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>


<body>
    <nav class="navbar navbar-expand-md navbar light bg-light mb-4 border">

    <a class="navbar-brand" href="{% url 'journaux_apprentissage:index' %}">
        Journal d'apprentissage</a>

    <button class="navbar-toogler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toogle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarCollapse">

        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" 
                    href="{% url 'journaux_apprentissage:topics' %}">Sujet</a>
            </li>
        </ul>

        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text">Bonjour {{ user.username }}.</span>
                </li>
                <li>
                    <form method="post" action="{% url 'utilisateurs:logout' %}">
                        {% csrf_token %}
                        <button name="submit" class="btn btn-primary ">Déconnexion</button>
                    </form>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" 
                    href="{% url 'utilisateurs:register' %}">S'inscrire</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" 
                    href="{% url 'utilisateurs:login' %}">Se connecter</a>
                </li>
            {% endif %}
        </ul>
    </div>
    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>

        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>

</body>

journal_apprentissage/journaux_apprentissage/templates/journaux_apprentissage/edit_entry.html
{% extends "journaux_apprentissage/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
    <h2>
        <p><a href="{% url 'journaux_apprentissage:topic' topic.id %}">
            {{ topic }}</a></p>
    <h2>
{% endblock page_header %}

{% block content %}

    <p>Modifier l'entrée :</p>
    <form method="post" action="{% url 'journaux_apprentissage:edit_entry' entry.id %}" 
        class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">
                Enregistrer les modifications.</button>
        {% endbuttons %}

    </form>

{% endblock content %}

journal_apprentissage/journaux_apprentissage/templates/journaux_apprentissage/index.html
{% extends "journaux_apprentissage/base.html" %}


{% block page_header %}

    <div class="jumbotron">
        <h1 class="display-4">Suivez vos apprentissages.</h1>

        <p class="lead">
            Créer votre propre journal d'apprentissage et conserver une liste de sujets 
            sur lesquels vous informer. Dés que vous acquérez de nouvelles connaissances 
            sur un sujet, créer une entrée qui résume ce que vous avez appris.
        </p>

        <a class="btn btn-lg btn-primary" href="{% url 'utilisateurs:register' %}"
            role="button">S'inscrire &raquo</a>
    </div>

{% endblock page_header %}

journal_apprentissage/journaux_apprentissage/templates/journaux_apprentissage/new_entry.html
{% extends "journaux_apprentissage/base.html" %}


{% load bootstrap4 %}

{% block page_header %}
    <h2>
        <p><a href="{% url 'journaux_apprentissage:topic' topic.id %}">
            {{ topic }}</a></p>
    <h2>
{% endblock page_header %}

{% block content %}

    <p>Ajouter une nouvelle entrée :</p>
    <form method="post" action="{% url 'journaux_apprentissage:new_entry' topic.id %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Ajouter l'entrée</button>
        {% endbuttons %}

    </form>

{% endblock content %}

journal_apprentissage/journaux_apprentissage/templates/journaux_apprentissage/new_topic.html
{% extends "journaux_apprentissage/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
    <h2>Ajouter un nouveau sujet :.<h2>
{% endblock page_header %}

{% block content %}

    <form method="post" action="{% url 'journaux_apprentissage:new_topic' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Ajouter le sujet</button>
        {% endbuttons %}

    </form>

{% endblock content %}

journal_apprentissage/journaux_apprentissage/templates/journaux_apprentissage/topic.html
{% extends "journaux_apprentissage/base.html" %}


{% block page_header %}
    <h3>{{ topic }}</h3>
{% endblock page_header %}


{% block content %}

    <p>
        <a href="{% url 'journaux_apprentissage:new_entry' topic.id %}">
            Ajouter une nouvelle entrée</a>
    </p>

    {% for entry in entries %}
        <div class="card mb-3">
            <h4 class="card-header">
                {{ entry.date_added|date:'d F Y, H:i' }}
                <small><a href="{% url 'journaux_apprentissage:edit_entry' entry.id %}">
                    Modifier l'entrée</a></small>
            </h4>
            <div class="card-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
    {% empty %}
        <p>Aucune entrée n'a encore été ajouté à ce sujet.</p>
    {% endfor %}


{% endblock content %}

journal_apprentissage/journaux_apprentissage/templates/journaux_apprentissage/topics.html
{% extends "journaux_apprentissage/base.html" %}


{% block page_header %}
    <h1>Sujets.</h1>
{% endblock page_header %}

{% block content %}

    <ul>
        {% for topic in topics %}
            <li><h3>
                <a href="{% url 'journaux_apprentissage:topic' topic.id %}">{{ topic }}</a>
            </h3></li>
        {% empty %}
            <li><h3>Aucun sujet n'a encore été ajouter.</h3></li>
        {% endfor %}
    </ul>

    <h3><a href="{% url 'journaux_apprentissage:new_topic' %}">
        Ajouter un nouveau sujet</a></h3>
    
{% endblock content %}